### ISSUE TITLE
Don't split sentences into several strings

### ISSUE THREAD

**Issue by tobifjellner** [eri-trabiccolo/childify-me#12]
Hi,
I can see a problem around https://plugins.trac.wordpress.org/browser/childify-me/trunk/class-childify-me.php#L422

```
					printf('<div id="cm-success" class="updated"><p>%1$s <span id="cm-ctheme"></span> %2$s</p>%3$s</div>',
						esc_html__( 'Child theme', 'childify-me' ),
						esc_html__( 'successfully created!', 'childify-me' ),
						( ! is_multisite() ) ?
							sprintf( '<a id="%3$s" class="button button-primary" href="%1$s" title="%2$s" tabindex="0">%2$s</a>',
								sprintf( '%1$s?theme=', esc_url( admin_url( 'customize.php' ) ) ),
								esc_html__( 'Preview and Activate', 'childify-me' ),
								'cm-preview'
							) :
							sprintf('<a id="%3$s" class="button button-primary" href="%1$s" title="%2$s" tabindex="0">%2$s</a>',
								esc_url( network_admin_url( 'themes.php' ) ),
								esc_html__( 'Go to Network Themes', 'childify-me' ),
								'cm-themes'
							)
					);

```
Here you output "Child theme successfully created!" and perhaps you even use some js to inject the name of that child theme into the string? 
It would be much better if the string to translate would contain the full sentence:
"Child theme ###CHILD-THEME-NAME### has been created!", adding a translators' comment that the ###-### thing will be replaced by the name of the new theme.
The translators are even more used to things like %1$s so you could inject the name that way, or the span tag pair.

I was about to draft a PR, but I think it's much easier for you to do this small change.

**Comment by eri-trabiccolo** [comment]
Hi there,
I think you're right, thanks for reporting this!

I'm not about to make this change soon, but I'm going to do it!
