### ISSUE TITLE
Text not centered vertically anymore in the button "Childify Me"

### ISSUE THREAD

**Issue by Nikeo** [eri-trabiccolo/childify-me#13]
- I use the latest version of WP 5.3.2
- active theme : Twenty Twenty
- Nimble Builder active
![2019-12-19_18-30-39](https://user-images.githubusercontent.com/3038156/71195216-c7709a00-228d-11ea-814b-0b5e7dd9efcd.jpg)

**Comment by eri-trabiccolo** [comment]
thanks man :D

**Comment by Nikeo** [comment]
'welcome !

**Comment by eri-trabiccolo** [comment]
fixed in https://github.com/eri-trabiccolo/childify-me/commit/b019d29b8bb9fd6a85536a4813a134c98247fd6b
