### ISSUE TITLE
Childify Me Spawns Security Warning

### ISSUE THREAD

**Issue by Jaxxon5** [eri-trabiccolo/childify-me#14]
Rocco,

WordPress security plugins (including WordFence and Really Simple Security) throw a warning for Childify Me:

**_Warning: This plugin has not been tested with your current version of WordPress._**

**_The Plugin "Childify Me" appears to be abandoned (updated 20 July 2021, tested to WP 5.8.10).
Type: Plugin Abandoned_**

It appears to work perfectly with the current iteration of WordPress (6.7.1) but it would be nice if whatever needs to be done to bring it "up to date" could be done -- I'm fairly certain that I'm not the only fan and user of Childify Me that has bumped into this issue.

Grazie mille!

D.J.

**Comment by eri-trabiccolo** [comment]
Thanks for reporting this, did some minor updates, gonna push a new release soon!
